### ISSUE TITLE
alire build error with gnarl_user and gnat_user

### ISSUE THREAD

**Issue by krcurtis** [JeremyGrosser/ravenscar_full_rp2040#1]
Hi,

I'm a new Ada user trying to use the Ravenscar profile with the RP2040 / pi pico board and following the instructions at https://pico-doc.synack.me/. When I've edited my .gpr file to use Ravenscar, I get these build errors:

> ravenscar_build.gpr:19:25: "gnarl_user" is not a valid directory
runtime_build.gpr:17:24: "gnat_user" is not a valid directory

Any suggestions?

Thanks!

**Comment by JeremyGrosser** [comment]
I've fixed this with the referenced commit. I also had some changes on the master branch that broke the build, which I've now reverted. Apologies for the inconvenience.

Let me know if you run into further problems... The Ravenscar build isn't very well tested and the documentation could use some improvement.

**Comment by krcurtis** [comment]
I can compile the ravenscar part with commit 506de1e7 (and I tried 1332130 commit). Next, I was getting an error about multiple definitions of __gnat_initialize_bootrom. After looking in the rp2040_hal repo, it looked like I needed to update my alire.toml:
```toml
[[pins]]
ravenscar_full_rp2040 = { url='https://github.com/JeremyGrosser/ravenscar_full_rp2040', commit='506de1e794ea5ab4bf2cd7673b800a1eac00f9d4' }
rp2040_hal = { url='https://github.com/JeremyGrosser/rp2040_hal', commit='098d7cf59a2c185fcd0acccf26bf7b9b4cdf9117'}
pico_bsp = { url='https://github.com/JeremyGrosser/pico_bsp', commit='1e02f4222109f9d27d854b4b0f4e83cb46b587fe'}

[configuration.values]
rp2040_hal.Use_Startup = false
rp2040_hal.Interrupts = "bb_runtimes"
``` 

Now I just need to figure how to get tasks working under the Ravenscar restrictions. I 'm guessing I can't use simple delays like:
```ada
RP.Device.Timer.Delay_Milliseconds (250);
```
anymore.

Thanks for the help!
